/control/verbose 0
/control/saveHistory
/run/verbose 0
/run/numberOfThreads 2

/run/initialize

/gps/particle proton
/gps/pos/type Surface
/gps/pos/shape Sphere
/gps/pos/centre 0 0 0 mm
/gps/pos/radius 100.0 mm

#/gps/pos/confine pHemisphere

/gps/ang/type cos
/gps/ang/mintheta 0 deg
/gps/ang/maxtheta 90 deg

/gps/ene/type Arb
/gps/hist/type arb
/gps/ene/emspec true
/gps/ene/diffspec false
/control/execute acc_p_solarmin.mac
/gps/hist/inter Lin

#/gps/ene/mono 400 MeV

/analysis/setActivation true
/analysis/h1/setActivationToAll true

/control/execute run_min.mac 

#/control/execute inactivation.mac 
#/control/loop run_min.mac counts 0 0 1
#/control/execute activation.mac 
#/control/loop run.mac counts 0 0 1
#/control/execute inactivation.mac 
#/control/loop run.mac counts 0 2 1
#/control/execute activation.mac
#/control/loop run.mac counts 0 0 1 

